packages = [

    # Baisc
    "devtools",
    "pacman",
    "renv",
    "languageserver",
    "IRkernel",
    "Rcpp",
    "RcppParallel",
    "reticulate",
    "lintr",
    "styler",
    "formatR",
    "BiocManager",

    # Tidyverse & dataIO
    "tidyverse",
    "dtplyr",
    "dbplyr",
    "data.table",
    "fst",
    "feather",
    "arrow",
    "DBI",
    "duckdb",
    "RMariaDB",
    "RPostgres",
    "RSQLite",

    # Report & Publish
    "rmarkdown",
    "blogdown",
    "bookdown",
    "distill",
    "rticles",
    "xaringan",
    "printr",
    "kableExtra",

    # Graphics
    "ggforce",
    "ggpmisc",
    "ggExtra",
    "ggfortify",
    "ggtext",
    "gghighlight",
    "ggthemes",
    "ggsci",
    "paletteer",
    "GGally",
    "ggridges",
    "ggraph",
    "lemon",
    "cowplot",
    "ggpubr",
    "corrplot",
    "ggbeeswarm",
    "ggrain",
    "ggThemeAssist",
    "shades",
    "visreg",
    "magick",
    "tidygraph",
    "wesanderson",
    "MetBrewer",
    "showtext",

    # Statistic
    "afex",
    "emmeans",
    "phia",
    "psych",
    "coin",
    "robustbase",
    "Rmisc",
    "lme4",
    "lmerTest",
    "gamm4",
    "mediation",
    "brms",
    "jmv",
    "sjPlot",
    "finalfit",
    "cocor",
    "skimr",
    "broom.mixed",
    "paran",
    "metafor",

    # Other
    "snow",
    "vitae",
    "rorcid",
    "RNifti",
    "R.matlab",
    "fMRIscrub",

]
